#!/usr/bin/env python3
"""
BillionMail + Namecheap DNS Auto-Configurator (IMPROVED VERSION)
Monitors BillionMail for new domains and automatically sets correct DNS records in Namecheap
"""

import json
import time
import os
import sys
import requests
import re
from datetime import datetime

# Configuration - Load from environment variables
BILLIONMAIL_BASE_URL = os.environ.get("BILLIONMAIL_BASE_URL", "http://127.0.0.1/api")
BILLIONMAIL_TOKEN = os.environ.get("BILLIONMAIL_TOKEN", "")

NAMECHEAP_API_USER = os.environ.get("NAMECHEAP_API_USER", "")
NAMECHEAP_API_KEY = os.environ.get("NAMECHEAP_API_KEY", "")

# Get actual server IP automatically or from env
VPS_IP = os.environ.get("VPS_IP", "")
if not VPS_IP:
    # Auto-detect IP
    try:
        import socket
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        VPS_IP = s.getsockname()[0]
        s.close()
    except:
        VPS_IP = "127.0.0.1"

# Secondary IPs from environment (comma-separated)
SECONDARY_IPS = [ip.strip() for ip in os.environ.get("SECONDARY_IPS", "").split(",") if ip.strip()]

# Namecheap Client IP must match VPS IP
NAMECHEAP_CLIENT_IP = VPS_IP

# DKIM Keys storage (generated by BillionMail for each domain)
DKIM_KEYS_PATH = "/opt/billionmail/rspamd-data/dkim"

# Validation settings
MIN_DKIM_KEY_LENGTH = 100  # Minimum valid DKIM key length


def log(message):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{timestamp}] {message}")
    sys.stdout.flush()


def validate_config():
    """Validate all required configuration is present"""
    errors = []
    
    if not BILLIONMAIL_TOKEN:
        errors.append("BILLIONMAIL_TOKEN not set")
    if not NAMECHEAP_API_USER:
        errors.append("NAMECHEAP_API_USER not set")
    if not NAMECHEAP_API_KEY:
        errors.append("NAMECHEAP_API_KEY not set")
    if not VPS_IP or VPS_IP == "127.0.0.1":
        errors.append("VPS_IP not properly detected")
    
    if errors:
        log("❌ Configuration errors:")
        for error in errors:
            log(f"   - {error}")
        log("Please set these environment variables or add to .env file")
        return False
    
    log(f"✅ Configuration valid. VPS IP: {VPS_IP}")
    return True


def get_billionmail_domains():
    """Fetch all domains from BillionMail API"""
    try:
        headers = {
            "Authorization": f"Bearer {BILLIONMAIL_TOKEN}",
            "Content-Type": "application/json"
        }
        response = requests.get(
            f"{BILLIONMAIL_BASE_URL}/domains/list?page=1&page_size=100",
            headers=headers,
            timeout=30
        )
        if response.status_code == 200:
            data = response.json()
            if data.get("success"):
                return data["data"]["list"]
        log(f"Error fetching domains: {response.status_code} {response.text[:200]}")
        return []
    except Exception as e:
        log(f"Exception fetching domains: {e}")
        return []


def get_dkim_keys(domain):
    """Get DKIM keys from BillionMail rspamd-data"""
    try:
        domain_path = f"{DKIM_KEYS_PATH}/{domain}"
        if not os.path.exists(domain_path):
            return None, None
        
        # Read default DKIM
        default_pub_path = f"{domain_path}/default.pub"
        default_key = ""
        if os.path.exists(default_pub_path):
            with open(default_pub_path, 'r') as f:
                content = f.read()
                # Extract the p= value
                match = re.search(r'p=([A-Za-z0-9+/=]+)', content.replace('"', '').replace('\n', '').replace('\t', ''))
                if match:
                    default_key = match.group(1)
        
        # Read short DKIM
        short_pub_path = f"{domain_path}/short.pub"
        short_key = ""
        if os.path.exists(short_pub_path):
            with open(short_pub_path, 'r') as f:
                content = f.read()
                match = re.search(r'p=([A-Za-z0-9+/=]+)', content.replace('"', '').replace('\n', '').replace('\t', ''))
                if match:
                    short_key = match.group(1)
        
        return default_key, short_key
    except Exception as e:
        log(f"Error reading DKIM keys for {domain}: {e}")
        return None, None


def validate_dkim_key(key, key_type="default"):
    """Validate DKIM key is proper length and format"""
    if not key:
        return False, "Key is empty"
    if len(key) < MIN_DKIM_KEY_LENGTH:
        return False, f"Key too short ({len(key)} chars, min {MIN_DKIM_KEY_LENGTH})"
    # Check for valid base64 characters
    if not re.match(r'^[A-Za-z0-9+/=]+$', key):
        return False, "Key contains invalid characters"
    return True, "Valid"


def set_namecheap_dns_with_retry(domain, default_dkim, short_dkim, max_retries=3):
    """Set DNS records in Namecheap with retry logic"""
    for attempt in range(max_retries):
        result = set_namecheap_dns(domain, default_dkim, short_dkim)
        if result:
            return True
        if attempt < max_retries - 1:
            log(f"   Retrying in 5 seconds... (attempt {attempt + 2}/{max_retries})")
            time.sleep(5)
    return False


def set_namecheap_dns(domain, default_dkim, short_dkim):
    """Set DNS records in Namecheap via API"""
    try:
        parts = domain.split('.')
        if len(parts) < 2:
            log(f"Invalid domain format: {domain}")
            return False
        
        sld = parts[0]
        tld = '.'.join(parts[1:])
        
        # Build SPF record with all IPs
        spf_ips = f"+ip4:{VPS_IP}"
        for ip in SECONDARY_IPS:
            spf_ips += f" +ip4:{ip}"
        spf_value = f"v=spf1 {spf_ips} ~all"
        
        # Build API URL
        base_url = "https://api.namecheap.com/xml.response"
        
        # Prepare hosts parameters
        params = {
            "ApiUser": NAMECHEAP_API_USER,
            "ApiKey": NAMECHEAP_API_KEY,
            "UserName": NAMECHEAP_API_USER,
            "Command": "namecheap.domains.dns.setHosts",
            "ClientIp": NAMECHEAP_CLIENT_IP,
            "SLD": sld,
            "TLD": tld,
            # A record for root
            "HostName1": "@",
            "RecordType1": "A",
            "Address1": VPS_IP,
            # A record for mail subdomain
            "HostName2": "mail",
            "RecordType2": "A",
            "Address2": VPS_IP,
            # MX record
            "HostName3": "@",
            "RecordType3": "MX",
            "Address3": f"mail.{domain}.",
            "MXPref3": "10",
            # SPF record
            "HostName4": "@",
            "RecordType4": "TXT",
            "Address4": spf_value,
            # DMARC record
            "HostName5": "_dmarc",
            "RecordType5": "TXT",
            "Address5": f"v=DMARC1;p=quarantine;rua=mailto:dmarc@{domain}",
            # DKIM default
            "HostName6": "default._domainkey",
            "RecordType6": "TXT",
            "Address6": f"v=DKIM1;k=rsa;p={default_dkim}",
            # DKIM short
            "HostName7": "short._domainkey",
            "RecordType7": "TXT",
            "Address7": f"v=DKIM1;k=rsa;p={short_dkim}",
        }
        
        response = requests.get(base_url, params=params, timeout=30)
        
        if 'Status="OK"' in response.text:
            log(f"✅ DNS records set successfully for {domain}")
            return True
        elif 'Invalid request IP' in response.text or '1011150' in response.text:
            log(f"⚠️  Namecheap API Error: VPS IP {NAMECHEAP_CLIENT_IP} not whitelisted!")
            log(f"   To fix: Add IP {NAMECHEAP_CLIENT_IP} to your Namecheap API whitelist")
            log(f"   Go to Namecheap Profile → Tools → API Access → Whitelist IP")
            return False
        elif '1011105' in response.text:
            log(f"⚠️  Namecheap API Error: ClientIP parameter invalid")
            log(f"   Current IP: {NAMECHEAP_CLIENT_IP}")
            log(f"   Make sure this IP is whitelisted in Namecheap API settings")
            return False
        else:
            log(f"❌ Failed to set DNS for {domain}: {response.text[:300]}")
            return False
            
    except Exception as e:
        log(f"Exception setting DNS for {domain}: {e}")
        return False


def refresh_billionmail_dns(domain):
    """Refresh DNS validation in BillionMail"""
    try:
        headers = {
            "Authorization": f"Bearer {BILLIONMAIL_TOKEN}",
            "Content-Type": "application/json"
        }
        response = requests.post(
            f"{BILLIONMAIL_BASE_URL}/domains/fresh_dns_records",
            headers=headers,
            json={"domain": domain},
            timeout=30
        )
        if response.status_code == 200 and response.json().get("success"):
            log(f"🔄 BillionMail DNS refreshed for {domain}")
            return True
        return False
    except Exception as e:
        log(f"Error refreshing DNS in BillionMail: {e}")
        return False


def process_domain(domain_data, processed_domains):
    """Process a single domain"""
    domain = domain_data.get("domain")
    if not domain:
        return False
    
    log(f"Processing domain: {domain}")
    
    # Get DKIM keys from BillionMail
    default_dkim, short_dkim = get_dkim_keys(domain)
    
    # Validate DKIM keys
    default_valid, default_msg = validate_dkim_key(default_dkim, "default")
    short_valid, short_msg = validate_dkim_key(short_dkim, "short")
    
    if not default_valid or not short_valid:
        log(f"⚠️  DKIM keys invalid for {domain}:")
        if not default_valid:
            log(f"   Default: {default_msg}")
        if not short_valid:
            log(f"   Short: {short_msg}")
        return False
    
    log(f"   DKIM keys validated (default: {len(default_dkim)} chars, short: {len(short_dkim)} chars)")
    
    # Set DNS in Namecheap with retry
    if set_namecheap_dns_with_retry(domain, default_dkim, short_dkim):
        # Wait a moment for DNS propagation
        time.sleep(2)
        # Refresh in BillionMail
        refresh_billionmail_dns(domain)
        return True
    return False


def main():
    """Main loop - check for domains and process them"""
    log("🚀 BillionMail + Namecheap DNS Auto-Configurator started")
    
    # Validate configuration
    if not validate_config():
        sys.exit(1)
    
    log(f"⏱️  Checking every 60 seconds...")
    log(f"   VPS IP: {VPS_IP}")
    log(f"   Secondary IPs: {', '.join(SECONDARY_IPS) if SECONDARY_IPS else 'None'}")
    
    processed_domains = set()
    check_counter = 0
    
    while True:
        try:
            check_counter += 1
            domains = get_billionmail_domains()
            
            # Refresh processed list every 10 checks (to catch re-added domains)
            if check_counter % 10 == 0:
                log("🔄 Refreshing processed domains cache...")
                processed_domains.clear()
            
            new_domains = 0
            for domain_data in domains:
                domain = domain_data.get("domain")
                
                if domain and domain not in processed_domains:
                    if process_domain(domain_data, processed_domains):
                        processed_domains.add(domain)
                        new_domains += 1
            
            if new_domains > 0:
                log(f"✅ Processed {new_domains} new domain(s)")
            
            time.sleep(60)  # Check every minute
            
        except KeyboardInterrupt:
            log("👋 Shutting down...")
            break
        except Exception as e:
            log(f"Main loop error: {e}")
            time.sleep(60)


if __name__ == "__main__":
    main()
