#!/usr/bin/env python3
"""
BillionMail + Namecheap DNS Auto-Configurator
Monitors BillionMail for new domains and automatically sets correct DNS records in Namecheap
"""

import json
import time
import os
import sys
import requests
from datetime import datetime

# Configuration
BILLIONMAIL_BASE_URL = "http://127.0.0.1/api"  # Internal Docker network
BILLIONMAIL_TOKEN = os.environ.get("BILLIONMAIL_TOKEN", "")

NAMECHEAP_API_USER = os.environ.get("NAMECHEAP_API_USER", "")
NAMECHEAP_API_KEY = os.environ.get("NAMECHEAP_API_KEY", "")
NAMECHEAP_CLIENT_IP = os.environ.get("VPS_IP", "")  # Whitelisted IP for API access

VPS_IP = os.environ.get("VPS_IP", "127.0.0.1")  # Main sending IP
SECONDARY_IPS = os.environ.get("SECONDARY_IPS", "").split(",") if os.environ.get("SECONDARY_IPS") else []

# DKIM Keys storage (generated by BillionMail for each domain)
DKIM_KEYS_PATH = "/opt/billionmail/rspamd-data/dkim"

def log(message):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{timestamp}] {message}")
    sys.stdout.flush()

def get_billionmail_domains():
    """Fetch all domains from BillionMail API"""
    try:
        headers = {
            "Authorization": f"Bearer {BILLIONMAIL_TOKEN}",
            "Content-Type": "application/json"
        }
        response = requests.get(
            f"{BILLIONMAIL_BASE_URL}/domains/list?page=1&page_size=100",
            headers=headers,
            timeout=30
        )
        if response.status_code == 200:
            data = response.json()
            if data.get("success"):
                return data["data"]["list"]
        log(f"Error fetching domains: {response.text}")
        return []
    except Exception as e:
        log(f"Exception fetching domains: {e}")
        return []

def get_dkim_keys(domain):
    """Get DKIM keys from BillionMail rspamd-data"""
    try:
        domain_path = f"{DKIM_KEYS_PATH}/{domain}"
        if not os.path.exists(domain_path):
            return None, None
        
        # Read default DKIM
        default_pub_path = f"{domain_path}/default.pub"
        default_key = ""
        if os.path.exists(default_pub_path):
            with open(default_pub_path, 'r') as f:
                content = f.read()
                # Extract the p= value
                import re
                match = re.search(r'p=([A-Za-z0-9+/=]+)', content.replace('"', '').replace('\n', '').replace('\t', ''))
                if match:
                    default_key = match.group(1)
        
        # Read short DKIM
        short_pub_path = f"{domain_path}/short.pub"
        short_key = ""
        if os.path.exists(short_pub_path):
            with open(short_pub_path, 'r') as f:
                content = f.read()
                match = re.search(r'p=([A-Za-z0-9+/=]+)', content.replace('"', '').replace('\n', '').replace('\t', ''))
                if match:
                    short_key = match.group(1)
        
        return default_key, short_key
    except Exception as e:
        log(f"Error reading DKIM keys for {domain}: {e}")
        return None, None

def set_namecheap_dns(domain, default_dkim, short_dkim):
    """Set DNS records in Namecheap via API"""
    try:
        parts = domain.split('.')
        if len(parts) < 2:
            log(f"Invalid domain format: {domain}")
            return False
        
        sld = parts[0]
        tld = '.'.join(parts[1:])
        
        # Use VPS IP for Namecheap API
        actual_ip = VPS_IP  # 85.121.241.162
        
        # Build SPF record with all IPs
        ALL_IPS = [VPS_IP] + SECONDARY_IPS
        spf_ips = ""
        for ip in ALL_IPS:
            spf_ips += f" +ip4:{ip}"
        spf_value = f"v=spf1 +a +mx{spf_ips} ~all"
        
        # Build API URL
        base_url = "https://api.namecheap.com/xml.response"
        
        # Prepare hosts parameters - using VPS IP for Namecheap API
        params = {
            "ApiUser": NAMECHEAP_API_USER,
            "ApiKey": NAMECHEAP_API_KEY,
            "UserName": NAMECHEAP_API_USER,
            "Command": "namecheap.domains.dns.setHosts",
            "ClientIp": actual_ip,
            "SLD": sld,
            "TLD": tld,
            # A record for root
            "HostName1": "@",
            "RecordType1": "A",
            "Address1": VPS_IP,
            # A record for mail subdomain
            "HostName2": "mail",
            "RecordType2": "A",
            "Address2": VPS_IP,
            # MX record
            "HostName3": "@",
            "RecordType3": "MX",
            "Address3": f"mail.{domain}.",
            "MXPref3": "10",
            # SPF record
            "HostName4": "@",
            "RecordType4": "TXT",
            "Address4": spf_value,
            # DMARC record
            "HostName5": "_dmarc",
            "RecordType5": "TXT",
            "Address5": f"v=DMARC1;p=quarantine;rua=mailto:dmarc@{domain}",
            # DKIM default
            "HostName6": "default._domainkey",
            "RecordType6": "TXT",
            "Address6": f"v=DKIM1;k=rsa;p={default_dkim}",
            # DKIM short
            "HostName7": "short._domainkey",
            "RecordType7": "TXT",
            "Address7": f"v=DKIM1;k=rsa;p={short_dkim}",
        }
        
        response = requests.get(base_url, params=params, timeout=30)
        
        if 'Status="OK"' in response.text:
            log(f"✅ DNS records set successfully for {domain}")
            return True
        elif 'Invalid request IP' in response.text or '1011150' in response.text:
            log(f"⚠️  Namecheap API Error: VPS IP {actual_ip} not whitelisted!")
            log(f"   To fix: Add IP {actual_ip} to your Namecheap API whitelist")
            log(f"   Go to Namecheap Profile → Tools → API Access → Whitelist IP")
            return False
        elif '1011105' in response.text:
            log(f"⚠️  Namecheap API Error: ClientIP parameter invalid")
            log(f"   Current IP: {actual_ip}")
            log(f"   Make sure this IP is whitelisted in Namecheap API settings")
            return False
        else:
            log(f"❌ Failed to set DNS for {domain}: {response.text[:200]}")
            return False
            
    except Exception as e:
        log(f"Exception setting DNS for {domain}: {e}")
        return False

def refresh_billionmail_dns(domain):
    """Refresh DNS validation in BillionMail"""
    try:
        headers = {
            "Authorization": f"Bearer {BILLIONMAIL_TOKEN}",
            "Content-Type": "application/json"
        }
        response = requests.post(
            f"{BILLIONMAIL_BASE_URL}/domains/fresh_dns_records",
            headers=headers,
            json={"domain": domain},
            timeout=30
        )
        if response.status_code == 200 and response.json().get("success"):
            log(f"🔄 BillionMail DNS refreshed for {domain}")
            return True
        return False
    except Exception as e:
        log(f"Error refreshing DNS in BillionMail: {e}")
        return False

def process_domain(domain_data):
    """Process a single domain"""
    domain = domain_data.get("domain")
    if not domain:
        return
    
    log(f"Processing domain: {domain}")
    
    # Get DKIM keys from BillionMail
    default_dkim, short_dkim = get_dkim_keys(domain)
    
    if not default_dkim or not short_dkim:
        log(f"⚠️  DKIM keys not found for {domain}, skipping...")
        return
    
    # Set DNS in Namecheap
    if set_namecheap_dns(domain, default_dkim, short_dkim):
        # Wait a moment for DNS propagation
        time.sleep(2)
        # Refresh in BillionMail
        refresh_billionmail_dns(domain)

def main():
    """Main loop - check for domains and process them"""
    log("🚀 BillionMail + Namecheap DNS Auto-Configurator started")
    log(f"⏱️  Checking every 60 seconds...")
    
    processed_domains = set()
    
    while True:
        try:
            domains = get_billionmail_domains()
            
            for domain_data in domains:
                domain = domain_data.get("domain")
                
                if domain and domain not in processed_domains:
                    process_domain(domain_data)
                    processed_domains.add(domain)
            
            time.sleep(60)  # Check every minute
            
        except KeyboardInterrupt:
            log("👋 Shutting down...")
            break
        except Exception as e:
            log(f"Main loop error: {e}")
            time.sleep(60)

if __name__ == "__main__":
    main()
