#!/bin/bash
# Auto-generated script to setup Noez IPs on boot
# Generated by noez_setup.sh
# This script runs on boot to re-add IPs after container restart

CONTAINER_NAME="billionmail-postfix-billionmail-1"
DOCKER_BRIDGE_GW="172.66.2.1"
DOCKER_BRIDGE="br-825cda742c28"
ALL_IPS="5.230.168.0 5.230.168.1 5.230.168.2 5.230.168.10 5.230.168.11 5.230.168.12"

# Wait for container to be ready
echo "Waiting for container $CONTAINER_NAME..."
for i in {1..30}; do
    if docker ps | grep -q "$CONTAINER_NAME"; then
        break
    fi
    sleep 2
done

# Get container PID
CONTAINER_PID=$(docker inspect -f '{{.State.Pid}}' $CONTAINER_NAME 2>/dev/null)
if [ -z "$CONTAINER_PID" ]; then
    echo "ERROR: Container not found!"
    exit 1
fi

echo "Container PID: $CONTAINER_PID"

# Add all Noez IPs to container loopback
for IP in $ALL_IPS; do
    echo "Adding $IP to container..."
    nsenter -t $CONTAINER_PID -n ip addr add $IP/32 dev lo 2>/dev/null || echo "$IP may already exist"
    nsenter -t $CONTAINER_PID -n ip rule add from $IP table 100 2>/dev/null || true
    nsenter -t $CONTAINER_PID -n ip route add default via $DOCKER_BRIDGE_GW table 100 2>/dev/null || true
done

# CRITICAL: Add routes on HOST to forward traffic to container
# This ensures reply packets go to container, not host
echo "Adding host routes for Noez IPs via bridge..."
for IP in $ALL_IPS; do
    # Delete any local route (if IP was on gre1)
    ip route del table local $IP 2>/dev/null || true
    # Add route via bridge to container
    ip route replace $IP dev $DOCKER_BRIDGE 2>/dev/null || ip route add $IP dev $DOCKER_BRIDGE 2>/dev/null || true
done

echo "All IPs added and routes configured successfully!"
