sign_headers = "from:sender:reply-to:subject:date:message-id:to:cc:mime-version:content-type:content-transfer-encoding:content-language:resent-to:resent-cc:resent-from:resent-sender:resent-message-id:in-reply-to:references:list-id:list-help:list-owner:list-unsubscribe:list-subscribe:list-post:list-unsubscribe-post:disposition-notification-to:disposition-notification-options:original-recipient:openpgp:autocrypt";

use_esld = false;

domain {
#BT_DOMAIN_DKIM_BEGIN

#affiliategrowth.shop_DKIM_BEGIN
affiliategrowth.shop {
   selectors [
    {
      path: "/var/lib/rspamd/dkim/affiliategrowth.shop/default.private";
      selector: "default";
    },
    {
      path: "/var/lib/rspamd/dkim/affiliategrowth.shop/short.private";
      selector: "short";
    }
  ]
}
#affiliategrowth.shop_DKIM_END

#b2bgrowth.shop_DKIM_BEGIN
b2bgrowth.shop {
   selectors [
    {
      path: "/var/lib/rspamd/dkim/b2bgrowth.shop/default.private";
      selector: "default";
    },
    {
      path: "/var/lib/rspamd/dkim/b2bgrowth.shop/short.private";
      selector: "short";
    }
  ]
}
#b2bgrowth.shop_DKIM_END

#aiemail.shop_DKIM_BEGIN
aiemail.shop {
   selectors [
    {
      path: "/var/lib/rspamd/dkim/aiemail.shop/default.private";
      selector: "default";
    },
    {
      path: "/var/lib/rspamd/dkim/aiemail.shop/short.private";
      selector: "short";
    }
  ]
}
#aiemail.shop_DKIM_END

#moescalesystem.shop_DKIM_BEGIN
moescalesystem.shop {
   selectors [
    {
      path: "/var/lib/rspamd/dkim/moescalesystem.shop/default.private";
      selector: "default";
    },
    {
      path: "/var/lib/rspamd/dkim/moescalesystem.shop/short.private";
      selector: "short";
    }
  ]
}
#moescalesystem.shop_DKIM_END

#aioutboundagents.shop_DKIM_BEGIN
aioutboundagents.shop {
   selectors [
    {
      path: "/var/lib/rspamd/dkim/aioutboundagents.shop/default.private";
      selector: "default";
    },
    {
      path: "/var/lib/rspamd/dkim/aioutboundagents.shop/short.private";
      selector: "short";
    }
  ]
}
#aioutboundagents.shop_DKIM_END

#b2baioutbound.shop_DKIM_BEGIN
b2baioutbound.shop {
   selectors [
    {
      path: "/var/lib/rspamd/dkim/b2baioutbound.shop/default.private";
      selector: "default";
    },
    {
      path: "/var/lib/rspamd/dkim/b2baioutbound.shop/short.private";
      selector: "short";
    }
  ]
}
#b2baioutbound.shop_DKIM_END

#moescale.xyz_DKIM_BEGIN
moescale.xyz {
   selectors [
    {
      path: "/var/lib/rspamd/dkim/moescale.xyz/default.private";
      selector: "default";
    },
    {
      path: "/var/lib/rspamd/dkim/moescale.xyz/short.private";
      selector: "short";
    }
  ]
}
#moescale.xyz_DKIM_END

#b2bscale.xyz_DKIM_BEGIN
b2bscale.xyz {
   selectors [
    {
      path: "/var/lib/rspamd/dkim/b2bscale.xyz/default.private";
      selector: "default";
    },
    {
      path: "/var/lib/rspamd/dkim/b2bscale.xyz/short.private";
      selector: "short";
    }
  ]
}
#b2bscale.xyz_DKIM_END

#moescaleb2b.site_DKIM_BEGIN
moescaleb2b.site {
   selectors [
    {
      path: "/var/lib/rspamd/dkim/moescaleb2b.site/default.private";
      selector: "default";
    },
    {
      path: "/var/lib/rspamd/dkim/moescaleb2b.site/short.private";
      selector: "short";
    }
  ]
}
#moescaleb2b.site_DKIM_END

#BT_DOMAIN_DKIM_END
}